### ISSUE TITLE
overlapCheck.sh: "unexpected number of lines"

### ISSUE THREAD

**Issue by gaponenko** [Mu2e/codetools#133]
Hi,

ssh mu2ebuild02
mu2einit
muse setup Offline v10_30_00
overlapCheck.sh /exp/mu2e/data/users/gandr/testcases/20240627-rootOverlaps/mu2e.gdml

says

ERROR - unexpected number of lines in root response: 20

**Comment by rlcee** [comment]
The unexpected number of lines is because it found an overlap, you should also see:
ERROR - overlaps found
We can suppress the number check if an overlap was found, would that make more sense?

**Comment by gaponenko** [comment]
Yes, because the current output looks like the script broke after reporting one overlap and there may be more overlaps.

Andrei

________________________________________
